# Generated by Django 4.2.19 on 2025-02-28 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('payment_dt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tax_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('MOBILE', 'MOBILE')], max_length=32)),
                ('served_by', models.CharField(blank=True, help_text='Staff or cashier handling the transaction', max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=125, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, editable=False, help_text='Amount paid in Ksh', max_digits=10)),
                ('tax_applied', models.DecimalField(decimal_places=2, editable=False, help_text='Tax applied in Ksh', max_digits=10, null=True)),
                ('qty', models.IntegerField(default=0, editable=False, help_text='Quantity of items', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='cart.order')),
                ('payment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='payment.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Orders',
            },
        ),
    ]
